import os
import re
import numpy as np
from optlib.constants import a0, gas_z
from optlib.utils import Error

class ElsepaError(Error):
    pass

class ElsepaWrapper:
    """
    Wrapper for parsing ELSEPA (Electron Elastic Scattering) data.
    Decoupled workflow: 
    1. write_input_files() -> Generates element-specific lub.in files.
    2. (User runs ELSEPA manually in those directories).
    3. parse_output_files() -> Reads the .dat files and computes material properties.
    """
    def __init__(self, material):
        self.mat = material

    @staticmethod
    def rmuf_from_number_density(n_atoms_cm3: float) -> float:
        """Calculates the Wigner-Seitz radius (Muffin-tin radius) in cm."""
        return (3.0 / (4.0 * np.pi * n_atoms_cm3))**(1.0 / 3.0)

    @staticmethod
    def parse_sigma(lines, key):
        """Extracts the cross-section in a0^2 from ELSEPA output."""
        line = next(l for l in lines if key in l)
        nums = re.findall(r"[-+]?\d+\.\d+E[+-]\d+", line)
        return float(nums[-1])

    def write_input_files(self, energy_array, dest_dir='.', mnucl=3, melec=4, mexch=1, minE=5.0):
        """
        Generates the 'lub.in' files for each element in the material.
        Creates subdirectories inside `dest_dir` for each element to avoid overwriting.
        """
        if self.mat.atomic_density is None:
            raise ValueError("Material atomic_density must be set before writing ELSEPA inputs.")

        energy_array = np.asarray(energy_array)
        used_energy = np.where(energy_array >= minE, energy_array, minE)
        unique_energies = np.unique(used_energy)
        
        n_atoms_cm3 = self.mat.atomic_density * 1e24

        for i, element in enumerate(self.mat.composition.elements):
            atomic_num = self.mat.composition.atomic_numbers[i]
            is_gas = atomic_num in gas_z
            rmuf_flag = 0 if is_gas else 1
            
            # Create a dedicated folder for this element (e.g., './elsepa_workspace/Cu')
            elem_dir = os.path.join(dest_dir, element)
            os.makedirs(elem_dir, exist_ok=True)
            
            input_filename = os.path.join(elem_dir, 'lub.in')
            
            with open(input_filename, 'w+') as fd:
                fd.write(f'IZ      {atomic_num}         atomic number                               [none]\n')
                fd.write(f'MNUCL   {mnucl}         rho_n (1=P, 2=U, 3=F, 4=Uu)                 [  3]\n')
                fd.write(f'NELEC   {atomic_num}         number of bound electrons                   [ IZ]\n')
                fd.write(f'MELEC   {melec}         rho_e (1=TFM, 2=TFD, 3=DHFS, 4=DF, 5=file)  [  4]\n')
                fd.write(f'MUFFIN  {rmuf_flag}          0=free atom, 1=muffin-tin model             [  0]\n')
                
                if not is_gas:
                    rmuf_val = self.rmuf_from_number_density(n_atoms_cm3)
                    fd.write(f'RMUF    {rmuf_val:.6e}  muffin-tin radius (cm)\n')
                    
                fd.write('IELEC  -1          -1=electron, +1=positron                    [ -1]\n')
                fd.write(f'MEXCH   {mexch}          V_ex (0=none, 1=FM, 2=TF, 3=RT)             [  1]\n')
                
                for e in unique_energies:  
                    fd.write(f'EV      {e}      kinetic energy (eV)                         [none]\n')
                    
        print(f"Generated ELSEPA input files in: {os.path.abspath(dest_dir)}")


    def parse_output_files(self, energy_array, source_dir='.', minE=5.0):
        """
        Parses the 'dcs_*.dat' files generated by ELSEPA from the element subdirectories.
        Maps the unique computed energies back to the user's original energy array.
        """
        if self.mat.atomic_density is None:
            raise ValueError("Material atomic_density must be set before parsing ELSEPA outputs.")

        energy_array = np.asarray(energy_array)
        used_energy = np.where(energy_array >= minE, energy_array, minE)
        unique_energies = np.unique(used_energy)
        
        n_energies = len(energy_array)
        sumweights = 0.0

        sigma_el_total = np.zeros(n_energies, dtype=float)
        sigma_tr_total = np.zeros(n_energies, dtype=float)
        decs_total = None
        decs_theta = None

        for i, element in enumerate(self.mat.composition.elements):
            weight = self.mat.composition.indices[i]
            sumweights += weight

            elem_dir = os.path.join(source_dir, element)
            
            unique_sig_el = {}
            unique_sig_tr = {}
            unique_decs = {}
            
            for ene in unique_energies:
                ene_str = '{:1.3e}'.format(int(np.round(ene))).replace('.', 'p').replace('+0', '0')
                output_dat = os.path.join(elem_dir, f"dcs_{ene_str}.dat")

                if not os.path.exists(output_dat):
                    raise ElsepaError(f"Missing ELSEPA output: '{output_dat}'. Did you run ELSEPA in this folder?")

                with open(output_dat, 'r') as fd:
                    lines = fd.readlines()

                unique_sig_el[ene] = self.parse_sigma(lines, "Total elastic cross section =")
                unique_sig_tr[ene] = self.parse_sigma(lines, "1st transport cross section =")

                data = np.loadtxt(output_dat, comments="#")
                th = np.deg2rad(data[:, 0])
                de = data[:, 3]  # DECS_A column

                if decs_theta is None:
                    decs_theta = th
                    
                if th.shape != decs_theta.shape or np.max(np.abs(th - decs_theta)) > 1e-12:
                    de = np.interp(decs_theta, th, de)

                unique_decs[ene] = de

            # Map unique results back to the full energy array
            if decs_total is None:
                decs_total = np.zeros((decs_theta.size, n_energies), dtype=float)
            
            element_decs = np.zeros((decs_theta.size, n_energies), dtype=float)

            for j, ene in enumerate(used_energy):
                sigma_el_total[j] += unique_sig_el[ene] * weight
                sigma_tr_total[j] += unique_sig_tr[ene] * weight
                element_decs[:, j] = unique_decs[ene]

            decs_total += element_decs * weight

        # Finalize weighted properties
        self.mat.sigma_el = sigma_el_total / sumweights
        self.mat.sigma_tr = sigma_tr_total / sumweights

        self.mat.emfp = 1.0 / (self.mat.sigma_el * a0**2 * self.mat.atomic_density)
        self.mat.trmfp = 1.0 / (self.mat.sigma_tr * a0**2 * self.mat.atomic_density)

        self.mat.decs_theta = decs_theta
        self.mat.decs = decs_total / sumweights

        norm_factor = np.trapz(self.mat.decs, self.mat.decs_theta, axis=0)
        self.mat.norm_decs = self.mat.decs / np.where(norm_factor > 0, norm_factor, 1.0)

        self.mat.e0_array = used_energy
        self.mat.original_e0_array = energy_array

        return self.mat.emfp, self.mat.decs
